name: Build npm
description: Steps for building a npm project
inputs:
  github-token:
    required: true
    description: "gpr"
runs:
  using: "composite"
  steps:
    - name: Npm build
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}
      run: |
        npm ci
        npm run test
        npm run build
      shell: bash
