name: Build npm
description: Steps for building a npm project
runs:
  using: "composite"
  steps:
    - name: Npm build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run build
      shell: bash
