name: Build gradle
description: Steps for building a gradle project
inputs:
  language:
    required: false
    type: string
    default: 'java'
  language-version:
    required: false
    type: string
    default: '21'
outputs:
  image: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK${{ inputs.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.version }}
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v3
    - name: Gradle build
      run: ./gradlew build
    - name: Build and push to GAR
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: oppgavehandtering
        dockerfile: Dockerfile
        #env:
        #ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}