name: Build maven
description: Steps for building a maven project
runs:
  using: "composite"
  steps:
    - name: Maven build
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        TEAM: oppgavehandtering
        REPO: ${{ github.repository }}
      run: mvn -B package --file pom.xml
