name: Build maven
description: Steps for building a maven project
inputs:
  java-version:
    required: true
    description: Version to build with
  snyk-token:
    required: true
    description: Snyk token
outputs:
  sbom:
    description: "SBOM file"
    value: target/bom.json
runs:
  using: "composite"
  steps:
    - name: Set up JDK${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Maven build
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        TEAM: oppgavehandtering
        REPO: ${{ github.repository }}
      run: mvn -B package --file pom.xml
      shell: bash
