name: Build, deploy

on:
  workflow_call:
    inputs:
      language:
        required: false
        type: string
        description: Language to build with
        default: 'java'
      version:
        required: false
        type: string
        description: Version to build with
        default: '21'
      build-tool:
        required: false
        type: string
        description: Build tool to use
        default: 'gradle'
      cluster:
        required: false
        type: string
        description: Nais cluster in dev to deploy to
        default: 'dev-fss'
      environments:
        required: false
        type: string
        description: Nais environments to deploy to
        default: 'dev'
jobs:
  build-gradle:
    if: ${{ inputs.build-tool == 'gradle' }}
    uses: navikt/oh-workflows/.github/workflows/build-gradle.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}
  deploy-main:
    uses: navikt/oh-workflows/.github/workflows/deploy-all-dev.yml@main
    needs: build-main
    secrets: inherit
    with:
      image: ${{ needs.build-main.outputs.image }}
      nav-cluster: ${{ inputs.cluster }}