name: Build

on:
  workflow_call:
    inputs:
      language:
        required: false
        type: string
        description: Language to build with
        default: 'java'
      language-version:
        required: false
        type: string
        description: Version to build with
        default: '21'
      build-tool:
        required: false
        type: string
        description: Build tool to use
        default: 'Gradle'
jobs:
  build:
    name: ${{ inputs.build-tool }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: Gradle build
        if: ${{ inputs.build-tool == 'Gradle' }}
        uses: ./.github/actions/build-gradle
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}