name: Build

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Version to build with
        default: '21'
      build-tool:
        required: false
        type: string
        description: Build tool to use
        default: 'Gradle'
    outputs:
      image:
        description: "Image"
        value: sdfsdf
jobs:
  build:
    name: ${{ inputs.build-tool }}
    runs-on: ubuntu-latest
    outputs:
      image: fsdfds
    steps:
      - name: Echo image to deploy
        run: |
          echo Deployer