name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: Version to build with
        default: '22'
      build-tool:
        required: false
        type: string
        description: Build tool to use
        default: 'npm'
    outputs:
      image:
        description: "Image"
        value: ${{ jobs.build.outputs.image }}
jobs:
  build:
    name: ${{ inputs.build-tool }}
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.build-tool }}
      - name: Build with npm
        if: ${{ (inputs.build-tool) == 'npm' }}
        uses: navikt/oh-workflows/.github/actions/build-npm@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: oppgavehandtering
          dockerfile: Dockerfile
      - name: Echo image to deploy
        run: |
          echo Deployer ${{ steps.docker-build-push.outputs.image }}