name: Build, deploy

on:
  workflow_call:
    inputs:
      language:
        required: false
        type: string
        description: Language to build with
        default: 'java'
      version:
        required: false
        type: string
        description: Version to build with
        default: '21'
      build-tool:
        required: false
        type: string
        description: Build tool to use
        default: 'gradle'
      cluster:
        required: false
        type: string
        description: Nais cluster in dev to deploy to
        default: 'dev-fss'
      environments:
        required: false
        type: string
        description: Nais environments to deploy to
        default: 'dev'
jobs:
  create-environments-array:
    name: create-environments array
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: create-strategy-matrix
        run: echo "environments-array=$(array=(${(s:,:)(${{ inputs.environments }})});printf '%s\n' ${array[@]} | jq -R . | jq -s -c .)" |
             echo "environments-array=$(environments= ${{ inputs.environments }};array=(${(s:,:)environments});printf '%s\n' ${array[@]} | jq -R . | jq -s -c .)"