
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cluster:
        required: true
        type: string
      environments:
        required: true
        type: string

jobs:
  deploy-dev:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{ inputs.cluster }}:oppgavehandtering
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        exclude:
          - environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: echo "Environment ${{ matrix.environment }}" |
          echo "Cluster dev-${{ inputs.cluster }}:oppgavehandtering" |
          echo "Nais .nais/app-${{ matrix.environment }}.yaml"
  deploy-prod:
    if: ${{ contains(inputs.environments, 'prod') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
    name: Prod
    runs-on: ubuntu-latest
    environment: ${{ inputs.cluster }}:oppgavehandtering
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cluster prod-${{ inputs.cluster }}:oppgavehandtering" |
          echo "Nais .nais/app-prod.yaml"