
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cluster:
        required: true
        type: string
      environments:
        required: true
        type: string

jobs:
  Dev:
    name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.cluster }}:oppgavehandtering
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        exclude:
          - environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/app-${{ matrix.environment }}.yaml
          VAR: image=${{ inputs.image }}