
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cluster:
        required: true
        type: string
      environments:
        required: true
        type: string

jobs:
  Dev:
    name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: dev-${{ inputs.cluster }}:oppgavehandtering
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        exclude:
          - environment: prod
    steps:
      - uses: actions/checkout@v4
      - id: ech
        run: echo "Environment ${{ matrix.environment }}" |
          echo "Cluster dev-${{ inputs.cluster }}:oppgavehandtering" |
          echo "Nais .nais/app-${{ matrix.environment }}.yaml"
  deploy-prod:
    if: ${{ contains(inputs.environments, 'prod') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/oh-workflows') }}
    name: Prod
    runs-on: ubuntu-latest
    environment: prod-${{ inputs.cluster }}:oppgavehandtering
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cluster prod-${{ inputs.cluster }}:oppgavehandtering" |
          echo "Nais .nais/app-prod.yaml"