
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cluster:
        required: true
        type: string
jobs:
  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/oh-workflows' }}
    name: Prod
    runs-on: ubuntu-latest
    environment: ${{ inputs.cluster }}:oppgavehandtering
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cluster ${{ inputs.cluster }}:oppgavehandtering" |
          echo "Nais .nais/app-prod.yaml"